name: build_account
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - development
      - staging

env:
  AWS_ROLE_ARN_DEV: arn:aws:iam::082954585471:role/rpf-infrastructure-role-dev
  AWS_ROLE_ARN_STG: arn:aws:iam::REPLACE_ME:role/rpf-infrastructure-role-stg
  AWS_ROLE_ARN_PROD: arn:aws:iam::REPLACE_ME:role/rpf-infrastructure-role-prod
  ECR_REPOSITORY: rpf-account-api

jobs:
  build_image:
    name: "build_image"
    permissions: write-all
    runs-on: ubuntu-latest
    if: startsWith(github.base_ref, 'development')
    defaults:
      run:
        working-directory: account/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN_DEV }}
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Get the version
        id: get-version
        env:
          MAIN_SHA: ${{ github.event.pull_request.head.sha }}
        run: echo "IMAGE_TAG=$(echo $MAIN_SHA | cut -c -7)" >> $GITHUB_OUTPUT
      - name: Build and tag image for Amazon ECR
        id: build-image
        env:
          ECR: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ steps.get-version.outputs.IMAGE_TAG }}
        run: docker build -t $ECR/$ECR_REPOSITORY-dev:$TAG .
      - name: Test image
        env:
          ECR: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ steps.get-version.outputs.IMAGE_TAG }}
        run: docker run --rm --entrypoint= $ECR/$ECR_REPOSITORY-dev:$TAG pytest --cov=backend/src --cov-branch
      - name: Push image to Amazon ECR
        env:
          ECR: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ steps.get-version.outputs.IMAGE_TAG }}
        run: docker push $ECR/$ECR_REPOSITORY-dev:$TAG

  confirm_image_pushed_dev:
    name: "confirm_image_pushed_dev"
    needs:
      - build_account_image
    if: startsWith(github.base_ref, 'development')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN_DEV }}
          aws-region: ap-northeast-1
      - name: Get the version
        id: get-version
        env:
          MAIN_SHA: ${{ github.event.pull_request.head.sha }}
        run: echo "IMAGE_TAG=$(echo $MAIN_SHA | cut -c -7)" >> $GITHUB_OUTPUT
      - name: Confirm pushed image
        id: get-digest
        env:
          TAG: ${{ steps.get-version.outputs.IMAGE_TAG }}
        run: |
          set -o pipefail
          DIGEST=`aws ecr describe-images --repository-name $ECR_REPOSITORY-dev --image-ids imageTag=$TAG | jq -r ".imageDetails[].imageDigest"`
          echo "DIGEST=$DIGEST" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Use image[tag:${{steps.get-version.outputs.IMAGE_TAG}}/digest:${{steps.get-digest.outputs.DIGEST}}].`
            })

  confirm_image_pushed_stg:
    name: "confirm_image_pushed_stg"
    needs:
      - build_account_image
    if: startsWith(github.base_ref, 'staging')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN_STG }}
          aws-region: ap-northeast-1
      - name: Get the version
        id: get-version
        env:
          MAIN_SHA: ${{ github.event.pull_request.head.sha }}
        run: echo "IMAGE_TAG=$(echo $MAIN_SHA | cut -c -7)" >> $GITHUB_OUTPUT
      - name: Confirm pushed image
        id: get-digest
        env:
          TAG: ${{ steps.get-version.outputs.IMAGE_TAG }}
        run: |
          set -o pipefail
          DIGEST=`aws ecr describe-images --repository-name $ECR_REPOSITORY-stg --image-ids imageTag=$TAG | jq -r ".imageDetails[].imageDigest"`
          echo "DIGEST=$DIGEST" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Use image[tag:${{steps.get-version.outputs.IMAGE_TAG}}/digest:${{steps.get-digest.outputs.DIGEST}}].`
            })

  confirm_image_pushed_prod:
    name: "confirm_image_pushed_prod"
    needs:
      - build_account_image
    if: startsWith(github.base_ref, 'production')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN_PROD }}
          aws-region: ap-northeast-1
      - name: Get the version
        id: get-version
        env:
          MAIN_SHA: ${{ github.event.pull_request.head.sha }}
        run: echo "IMAGE_TAG=$(echo $MAIN_SHA | cut -c -7)" >> $GITHUB_OUTPUT
      - name: Confirm pushed image
        id: get-digest
        env:
          TAG: ${{ steps.get-version.outputs.IMAGE_TAG }}
        run: |
          set -o pipefail
          DIGEST=`aws ecr describe-images --repository-name $ECR_REPOSITORY-prod --image-ids imageTag=$TAG | jq -r ".imageDetails[].imageDigest"`
          echo "DIGEST=$DIGEST" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Use image[tag:${{steps.get-version.outputs.IMAGE_TAG}}/digest:${{steps.get-digest.outputs.DIGEST}}].`
            })

  confirm_image_pushed:
    needs:
      - confirm_image_pushed_dev
      - confirm_image_pushed_stg
      - confirm_image_pushed_prod
    if: failure() == false && contains(needs.*.result, 'cancelled') == false
    runs-on: ubuntu-latest
    steps:
      - run: echo "$json"
        env:
          json: ${{ toJSON(needs) }}

